version: '3'

services:
  app:
    build:
      context: docker/app
    ports:
      - 22080:80
    volumes:
      - ./app:/var/www/html
      - ./docker/app/logs/nginx:/var/log/nginx
      - ./docker/app/.composer:/root/.composer
    depends_on:
      - postgres

  postgres:
    build:
      context: docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES_WITH_POSTGIS=laravel
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    networks:
      default:
        aliases:
          - laravel.localhost
