package config

var (
	SERVICE_GRACEFUL_TIMEOUT = "SERVICE_GRACEFUL_TIMEOUT"
	SERVICE_POSTGRES_DNS     = "SERVICE_POSTGRES_DNS"
	SERVICE_REDIS_DNS        = "SERVICE_REDIS_DNS"
	DEBUG                    = "DEBUG"
)
